name: Create and publish a Docker image to hub.docker.com

on:
  push:
    branches: 
     - main


jobs:
  build:
    if: github.repository == 'lfdelzam/Gene_catalog_Rshiny'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: lfdelzam/Gene_catalog_Rshiny
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: Dockerfile
          tags: "latest"
